### ISSUE TITLE
Bug: GUI.py Tab 1 - recover files

### ISSUE THREAD

**Issue by 3C-SCSU** [3C-SCSU/Avatar#104]
Recovering file/directories deleted erroneously:

Apparently happened that the directory [gui_windows] currently on:
![image](https://github.com/3C-SCSU/Avatar/assets/114175379/ed474972-eee4-453c-80bf-b89427ed5081)

Should also exist in the brain*app/client - and was delete, accidentally:
![image](https://github.com/3C-SCSU/Avatar/assets/114175379/b34e0728-4e89-4c30-bbfe-82b9f0cedef7)
That's what is causing the error for the GUI.py; 

Quick reference:
https://www.youtube.com/watch?v=-UMFF4_65dw
https://www.smashingmagazine.com/2023/12/recovering-deleted-files-git-working-tree/

**Comment by etan91011** [comment]
done https://github.com/3C-SCSU/Avatar/pull/105

**Comment by 3C-SCSU** [comment]
It works now. Bug fixed.
