### ISSUE TITLE
Installation: steps to have Avatar with Qt\QML

### ISSUE THREAD

**Issue by 3C-SCSU** [3C-SCSU/Avatar#106]
Create a Wiki documentation with the steps needed to have the Avatar installation working using Qt\QML.

**Comment by divyapdarsi** [comment]
Hello Professor,

Please find the Documentation for Avatar with Qt/QML.

https://github.com/3C-SCSU/Avatar/wiki/Avatar-installation-using-Qt%5CQML

Please review and provide your feedback.

**Comment by 3C-SCSU** [comment]
@divyapdarsi Kudos to you! Well done. Good job.
