### ISSUE TITLE
Install Native Linux on Chromebook

### ISSUE THREAD

**Issue by divyapdarsi** [3C-SCSU/Avatar#137]
**Get Native Linux to run on Chromebook:**

1. Follow steps provided in the reference; (2 points)
2. Have any of the suggested Linux ISO/Flavors used in the installation;(2 points)
3. Install Native Linux to run on Chromebook, removing ChromeOS; detailed any troubleshooting necessary to finish the installation. (2 points)
4. Make a power point presentation (~ 4-5 minutes), recording the video presentation about the project implementation methodologies and approach. (2 points)
5. Submit: a short video showing the program in action and include a short video with the presentation, source code and documentation with the steps. (2 points) 

**Reference Links** 

https://askubuntu.com/questions/898833/how-to-uninstall-chrome-os-and-install-ubuntu-16-04-fully-not-crouton-on-a-chr

https://www.youtube.com/watch?v=z6oyqrrXTLM

https://docs.chrultrabook.com/

**Comment by 3C-SCSU** [comment]
Ticket solved:
https://github.com/3C-SCSU/Avatar/pull/138
