### ISSUE TITLE
EPIC: MVP_GUI

### ISSUE THREAD

**Issue by j-knudson** [3C-SCSU/Avatar#19]
Epic: Tasks associated with the MVP gui here: https://github.com/3C-SCSU/Avatar/blob/main/brainwave-prediction-app/GUI.py

This is a Minimum Viable Produce GUI used for initial testing and live demos. The GUI itself will be replaced, but the brainflow connection to the Open BCI, and information transfer to the server should be re-used when it is replaced. 

- [x] MVP_GUI: Manual Drone Control 
- [ ] MVP_GUI: Brainwave Reading 
- [ ] #20

**Comment by 3C-SCSU** [comment]
GUI for data transfer is implemented.
