### ISSUE TITLE
MVP_GUI - FEATURE: Transfer Raw Data

### ISSUE THREAD

**Issue by j-knudson** [3C-SCSU/Avatar#20]
Parent Epic: MVP_GUI #19 
## Feature Description:  

The MVP_GUI is able to handle transferring of raw data as part of a brainwave donation to the VPS using the file transfer script. 
 - See Brainwave Donation: https://github.com/3C-SCSU/Avatar/wiki/Brainwave-Donation-Procedure
 - File Transfer Script:  https://github.com/3C-SCSU/Avatar/blob/main/file-transfer/sftp.py

### Stories: 
  - [ ]  #21
  - [ ]  #22
  - [ ] Create a .env or alternative system for SSH details

**Comment by 3C-SCSU** [comment]
GUI for data transfer is implemented.
