### ISSUE TITLE
Data Transfer Window

### ISSUE THREAD

**Issue by j-knudson** [3C-SCSU/Avatar#21]
Parent Feature: Transfer Raw Data #20
Connected Issue: #22 
## Technical Details: 
The current GUI.py file has a disabled button to open a Transfer Data screen. The transfer data screen is responsible for sending raw Brainwave data to the VPS. This screen will need an option to specify the data to be transferred. Either by allowing the user to input a file path to a directory location or selecting a folder with the stored data. It will also need a button that will be used to initiate data transfer using the file transfer script 

## Acceptance Criteria: 
- The main screen of GUI.py has a functional button to open the transfer data screen
- The transfer data screen has an option to select a locally stored directory for transfer
- The transfer data screen has a button that will be linked to the file transfer script

**Comment by KINGTUT10101** [comment]
I think this was finished in this PR:
https://github.com/3C-SCSU/Avatar/commit/f323f350486ac56444fc9116057469d1731b821e

**Comment by 3C-SCSU** [comment]
GUI for data transfer is implemented.
