### ISSUE TITLE
Connect the Transfer Data Window with the file transfer script

### ISSUE THREAD

**Issue by j-knudson** [3C-SCSU/Avatar#22]
Parent Feature:  #20 
Blocker Issue:  #21 
Connected Issue: #23 
## Technical Details: 
Once the GUI screen for a data transfer window is completed with ticket #21, the file transfer script will need to be connected to the transfer data button. That file has a section to be updated with private data. Make sure not to include that data as part of a commit to the repository. There is a connected issue for handling of that data. The script may need to be updated to function with the GUI source input. The script currently functions through the command line receiving an argument for the source and destination directories. The destination directory on the server will need to be established for use with the script.    

Transfer Script: https://github.com/3C-SCSU/Avatar/blob/main/file-transfer/sftp.py

## Acceptance Criteria: 
- Pressing the transfer data button on the GUI will send data from a specified source directory to the VPS
- No private data is included as part of the commits for this story

**Comment by 3C-SCSU** [comment]
GUI for data transfer is implemented.
