### ISSUE TITLE
Donation Data File transfer .env

### ISSUE THREAD

**Issue by j-knudson** [3C-SCSU/Avatar#23]
Parent Feature: #20 
## Technical Details: 
Using secrets, a .env, creating a server endpoint, or some other method configure the sftp.py script to connect to the VPS without sharing SSH or IP Address information to github. 

Script: https://github.com/3C-SCSU/Avatar/blob/main/file-transfer/sftp.py
## Acceptance Criteria 
Raw brainwave data files can be transferred to the VPS without each user having to manually configure a file transfer script.

**Comment by 3C-SCSU** [comment]
GUI for data transfer is implemented.
