### ISSUE TITLE
Research Ice Drive

### ISSUE THREAD

**Issue by j-knudson** [3C-SCSU/Avatar#26]
Parent Feature: #25

## Technical Details: 
The club has an Ice Drive account. https://icedrive.net/apps/desktop-laptop   Research if Ice Drive is able to function as a Data Lake repository and how to connect to Ice Drive for transferring and loading data. 

## Acceptance Criteria: 
If Ice Drive is a viable Data Lake Repository: 
 - Find information/documentation on how to transfer data to Ice Drive via script
 - Find information/documentation on how to load data from Ice Drive on the VPS 
 - Implementation for those tasks will be on separate tickets: 
             #27

**Comment by cobaltburn** [comment]
after looking at ice drive the only way you are able to up load data is directly through their application, and as of may they have not began work on a public api for uploading files, we will need to look into alternative bucket storage
