### ISSUE TITLE
Keep Drone Alive Function

### ISSUE THREAD

**Issue by j-knudson** [3C-SCSU/Avatar#30]
## Business Requirements: 
The Tello Drone will automatically land after 15 seconds without receiving new input. It often takes close to this time limit to record, process, and receive a prediction response from a brainwave. The current work around is a "Keep Alive" button that triggers a query to the drone battery so it neither moves nor triggers the auto lander. Currently, this button must be manually pressed. We would like this functionality to be converted to a "Keep Alive" mode that can be toggled on and off and will run the keep alive action in a timed loop. 

## Technical Details: 

- Create a button for a keep alive toggle available from the brainwave prediction window. 

- Connect the button to a function or thread that will run a loop sending the drone a non-movement signal every 10 seconds. (Current keep alive button uses ` tello.query_battery() `)
- Provide user feedback indicating the state of the keep alive toggle. 

## Acceptance Criteria: 
Users can toggle a mode that keeps the drone from automatically landing. When the user is running a live prediction demo, there is an indicator available as to whether the keep alive mode is being used or not.

**Comment by 3C-SCSU** [comment]
Duplicated. This issue is solved and merged:
https://github.com/3C-SCSU/Avatar/pull/34
