### ISSUE TITLE
EPIC: GUI_V2

### ISSUE THREAD

**Issue by j-knudson** [3C-SCSU/Avatar#31]
The current GUI: #19 is an MVP placeholder used in live demonstrations. The goal is to replace that GUI with an enhanced cross-platform, distributable, desktop (and mobile?) application that will fully replace the current MVP GUI.

This GUI will need all features of the existing GUI 

- Home screen
- Manual Drone Control 
- Transfer data from a new brainwave donation
- Live Demo (Stream brainwave to prediction endpoint, receive prediction, pilot drone with prediction)

New features could include: 
- Login System
- New Ideas? 

A long term goal of the Avatar project is to create a containerized, scalable solution using containers and Kubernetes. Design decisions should keep that goal in mind, and it may require additional research during planning.  

GUI V2 is in the planning stage and open to any and all discussion in the comment section here, including feedback and issues from the MVP GUI, suggestions for additional features, and potential risks or issues with the development plan.  

 - [x] #40 
      - [x] #32 
      - [ ]  #33
- [ ]  GUI_V2: Design Documents
- [ ]  TODO: Implementation Features (This section will be expanded after design discussions are completed)

**Comment by 3C-SCSU** [comment]
That new GUI Tab was implemented and added to the code repo.
