### ISSUE TITLE
WIREFRAME: Homescreen

### ISSUE THREAD

**Issue by j-knudson** [3C-SCSU/Avatar#32]
**Parent Epic:** GUI_V2 #31 

# REPEATABLE
Multiple people can work on this story. Once a wireframe is completed, post it for discussion in the wireframes channel on the club discord. 

## Business Requirements
See the parent story for general details on the replacement GUI. We need a general home-screen from which the user will be able to access the three current primary functionalities: 
- Manual Drone Control
- Save brainwave donation data
- Brainwave Piloting: Control the drone through predictions on a brainwave stream

Considerations: At the moment there is not a system for authentication or specific users. If an authentication system is added, we would want some form of banner or navigation to a user profile section. 

## Technical Requirements
Using [Figma](https://www.figma.com/) create a wireframe with your design idea for the home screen. The options for the design are open ended, and the wireframing will also serve as brainstorming and opportunity for UI/UX discussion. 

## Acceptance Criteria

- A wireframe is created in Figma. 
- The wireframe includes, either through direct ability on the homescreen or links to navigate to alternative screens, the three primary functionalities 
 - For Midterm/Bounty submit a PR with a file to a directory named `Wireframes`

**Comment by 3C-SCSU** [comment]
That new GUI Tab was implemented and added to the code repo.
