### ISSUE TITLE
WIREFRAME: Manual Drone Control

### ISSUE THREAD

**Issue by j-knudson** [3C-SCSU/Avatar#33]
**Parent Epic:** GUI_V2 #31 

# REPEATABLE
Multiple people can work on this story. Once a wireframe is completed, post it for discussion in the wireframes channel on the club discord. 

## Background
See the parent story for general details on the replacement GUI. We need a screen from which the user will be able to pilot the drone. The primary purpose of this functionality is to be able to test programmatically controlling the drone outside of brainwave piloting. The current MVP_GUI uses a button system: 

![Image](https://github.com/3C-SCSU/Avatar/assets/71792574/9a602b69-3a23-4b7c-bf09-a8a91aa33256)

The wireframe does not need to be similar to this button layout. It could use a joystick or some other control method. There is also an option to connect to the drone camera that is not implemented in the MVP version and could be in the improved version. In the lab, there are several different drone control apps available from the lab phones that can be used for alternative ideas on a piloting options. 

## Business Requirements 

Users can manually pilot a drone with the application. 

## Technical Requirements
Using [Figma](https://www.figma.com/) create a wireframe with your design idea for the manual piloting screen. The options for the design are open ended, and the wireframing will also serve as brainstorming and opportunity for UI/UX discussion. 

- There needs to be an ability to trigger connecting to the drones's wifi. 
- Drone commands we need to be able to test:
  - Takeoff
  - Land
  - Up 
  - Down
  - Rotate Counterclockwise
  - Rotate Clockwise
  - Left
  - Right
  - Forward
  - Backward
  - Flip

## Acceptance Criteria

- A wireframe is created in Figma. 
- The wireframe includes some ability for the user of this screen to interact with all required drone command functionalities.
-  - For Midterm/Bounty submit a PR with a file to a directory named `Wireframes`

**Comment by 3C-SCSU** [comment]
GUI is improved: new version uses tabs.
