### ISSUE TITLE
Feature: GUI_V2 Wireframes

### ISSUE THREAD

**Issue by j-knudson** [3C-SCSU/Avatar#40]
Parent Epic: GUI_V2 #31 

## Background
A wireframe is similar to blueprint or mockup of a screen to create and discuss different design possibilities prior to coding. The current GUI did not go through a wireframing or design process. It uses a system of windows to handle each of the core functionalities. For the V2 GUI, we would like to take a more planned approach starting with wireframes and UI/UX discussion. 

## Technical Details
Using software of your choice (preference for Figma but not required) create designs that will be used for the implementation of the V2 GUI. The implementation should include the functionalities in the current GUI:

- Home Screen
- Manual Drone Control
- Transfer data from brainwave donations
- Live Prediction 

The designs can also include any new features. The design is completely open ended, so long as it includes the core functionalities. It can be included in one window, split to their own windows, tabs, expandable drawers, or any other idea.

 There are issues for breaking the wireframing of core functionalities into workable tasks. If not using a windowed approach, treat the issue as a description of the needed functionality 
- [ ] #32 
- [x] #33

**Comment by 3C-SCSU** [comment]
A new GUI Tab was implemented.
