### ISSUE TITLE
Create S3 data bucket: setup and test connectivity

### ISSUE THREAD

**Issue by 3C-SCSU** [3C-SCSU/Avatar#75]
Create a S3 data bucket and setup and test connectivity: deploying it to the Cloud Computing Server.
Reach out to get access to the server and the current data bucket provider.

**Comment by divyapdarsi** [comment]
Hello Guys,

Please find the below wiki link with steps by steps process to create a S3 Bucket with Connectivity 

https://github.com/3C-SCSU/Avatar/wiki/Create-S3-data-bucket:-setup-and-test-connectivity-%2375

**Comment by 3C-SCSU** [comment]
Good job!
