### ISSUE TITLE
Qt QML: Radio Button - [Synthetic | Live] FLy Drone

### ISSUE THREAD

**Issue by KINGTUT10101** [3C-SCSU/Avatar#85]
Using the Qt Creator / QML Python:

1. Add the radio button that will let user select to fly the drone with Synthetic recorded data or Live brain reading; (3points)
2. Test it and check making the program works as expected; (2points)
3. Submit on D2L: short presentation going over the code, and demo showing the program working; (3points)
4. After (3); check if your code is approved to enter the Avatar code repo; if so, do pull request on GitHub to have your code merged; (2points)

IMPORTANT:
lines 21/22 are for synthetic data and use those when testing deployments without headsets; 
![image](https://github.com/3C-SCSU/Avatar/assets/114175379/6c2bacc4-3fd8-40d5-a3ac-b59cf13b506c)
Lines 16-18 are the ones when using the actual headset - so you just flip flop which ones are commented;
![image](https://github.com/3C-SCSU/Avatar/assets/114175379/d3101d2d-4c85-49a0-922b-858d34495c44)

https://github.com/3C-SCSU/Avatar/wiki/Running-Avatar

![image](https://github.com/3C-SCSU/Avatar/assets/114175379/6b98594f-b11c-4d3b-828c-811c32704e48)

Note - reason to move from PySimpleGUI to QT:
It might be best to move away from pysimplegui to keep avatar accessible to everyone https://news.ycombinator.com/item?id=39369353

**Comment by 3C-SCSU** [comment]
https://github.com/3C-SCSU/Avatar/pull/121
